# Configuration file for GitHub Dependabot: https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
- package-ecosystem: "gitsubmodule"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 1000
