$schema: https://raw.githubusercontent.com/remal-github-actions/sync-with-template/main/config.schema.json
includes:
- '.agents/rules/**'
- '.claude/rules/**'
- '.github/**'
- '.mergify/*'
- '.gitattributes'
- '.gitignore'
- '.editorconfig'
- 'retry-connection-timeouts'
- '*-retry-connection-timeouts'
- 'retry-connection-timeouts-*'
- 'checkstyle.xml'
- 'lombok.config'
- 'eslint.config.*'
- '.eslint*'
- '.prettier*'
- '.yarn*'
excludes:
- '.github/workflows/*template*-cleanup.*'
- '.github/*template*-cleanup/**'
modifiable-sections-exclusions:
- '.yarn/plugins/**'
- '.yarn/releases/**'
