#!/usr/bin/env bash

DELAY_INTERVAL=60

HIGHLIGHT_COLOR='\033[1;33m'
TRACE_COLOR='\033[1;90m'
NO_COLOR='\033[0m'

RESULT=0

for ATTEMPT in $(seq 1 2); do
    if [ "$ATTEMPT" -gt 1 ]; then
        echo -e "\n${HIGHLIGHT_COLOR}Waiting $DELAY_INTERVAL seconds before attempt #$ATTEMPT...${NO_COLOR}\n"
        sleep "$DELAY_INTERVAL"
    fi

    LOGFILE=$(mktemp)
    #echo -e "${TRACE_COLOR}Executing $* command and storing its output to log file $LOGFILE${NO_COLOR}"
    echo "::debug::Executing $* command and storing its output to log file $LOGFILE"

    "$@" 2>&1 | tee "$LOGFILE"
    RESULT="${PIPESTATUS[0]}"

    if [ "$RESULT" -eq 0 ]; then
        exit 0

    elif STR="connect timed out" && grep -q -i "$STR" "$LOGFILE"; then
        echo "::warning::'$STR' found in $* command log file $LOGFILE"

    elif STR="Connect Timeout Error" && grep -q -i "$STR" "$LOGFILE"; then
        echo "::warning::'$STR' found in $* command log file $LOGFILE"

    elif STR="Could not install Gradle distribution from" && grep -q -i "$STR" "$LOGFILE"; then
        echo "::warning::'$STR' found in $* command log file $LOGFILE"

    elif STR="Timeout has been exceeded" && grep -q -i "$STR" "$LOGFILE"; then
        echo "::warning::'$STR' found in $* command log file $LOGFILE"

    elif STR="Could not pack tree 'jvmArgumentProviders.jacocoAgent" && grep -q -i "$STR" "$LOGFILE"; then
        echo "::warning::'$STR' found in $* command log file $LOGFILE"

    elif STR="Could not get resource" && grep -q -i "$STR" "$LOGFILE"; then
        echo "::warning::'$STR' found in $* command log file $LOGFILE"

    elif STR="Could not resolve all files for configuration" && grep -q -i "$STR" "$LOGFILE"; then
        echo "::warning::'$STR' found in $* command log file $LOGFILE"

    elif STR="Received status code 429 from server" && grep -q -i "$STR" "$LOGFILE"; then
        echo "::warning::'$STR' found in $* command log file $LOGFILE"

    elif STR="Server returned HTTP response code: 50" && grep -q -i "$STR" "$LOGFILE"; then
        echo "::warning::'$STR' found in $* command log file $LOGFILE"

    else
        break
    fi
done

exit "$RESULT"
