#!/usr/bin/env bash
set -u

DELAY_INTERVAL=60
MAX_ATTEMPTS=3

HIGHLIGHT_COLOR=$'\033[1;33m'
NO_COLOR=$'\033[0m'

RETRY_PATTERNS=(
  "connect timed out"
  "Connect Timeout Error"
  "Could not install Gradle distribution from"
  "Timeout has been exceeded"
  "Could not pack tree 'jvmArgumentProviders.jacocoAgent"
  "Could not get resource"
  "Could not resolve all files for configuration"
  "Received status code 429 from server"
  "Received status code 50"
  "Server returned HTTP response code: 50"
  "ArtifactNotFoundException: Could not find gradle-api"
)

LOGFILES=()
trap 'rm -f "${LOGFILES[@]}"' EXIT

RESULT=0

printf -v CMD '%q ' "$@"

for ((ATTEMPT = 1; ATTEMPT <= MAX_ATTEMPTS; ATTEMPT++)); do
    if (( ATTEMPT > 1 )); then
        printf '\n%sWaiting %s seconds before attempt #%s...%s\n\n' \
            "$HIGHLIGHT_COLOR" "$DELAY_INTERVAL" "$ATTEMPT" "$NO_COLOR"
        sleep "$DELAY_INTERVAL"
    fi

    LOGFILE=$(mktemp)
    LOGFILES+=("$LOGFILE")

    echo "::debug::Executing ${CMD}command and storing its output to log file $LOGFILE"

    "$@" 2>&1 | tee "$LOGFILE"
    RESULT="${PIPESTATUS[0]}"

    if (( RESULT == 0 )); then
        exit 0
    fi

    RETRY_REASON=
    for STR in "${RETRY_PATTERNS[@]}"; do
        if grep -Fqi -- "$STR" "$LOGFILE"; then
            RETRY_REASON="$STR"
            break
        fi
    done

    if [[ -n "$RETRY_REASON" ]]; then
        echo "::warning::'$RETRY_REASON' found in command log file $LOGFILE"
    else
        break
    fi
done

exit "$RESULT"
