name: Automatic release

on:
  schedule:
  - cron: '14 8 * * 3' # sync-with-template: adjust
  workflow_dispatch: { }

defaults:
  run:
    shell: bash

jobs:
  automatic-release:
    name: Automatic release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency: automatic-release
    steps:
    - name: Automatic release
      uses: remal-github-actions/automatic-release@v1
      with:
        githubToken: ${{secrets.PUSH_BACK_TOKEN}}
        versionIncrementMode: 'patch'
        versionTagPrefix: 'v'
        expectedFilesToChange: |
          gradle-plugin-api-dependencies.txt
        allowedCommitPrefixes: |
          [push-back]
          [noci]
          [no-ci]
          [ci]
          [release-later]
          [doc]
          [documentation]
          [no-changelog]
          Update README.md
          Update renovate.json5
          Update renovate.json
        skippedChangelogCommitPrefixes: |
          [push-back]
          [no-changelog]
        dependencyUpdatesPullRequestLabels: |
          dependencies
        miscPullRequestLabels: |
          sync-with-template
          remal-gradle-plugins-toolkit
        actionPathsAllowedToFail: |
          .github/workflows/automatic-release.yml
          .github/workflows/bump-repository-activity.yml
          .github/workflows/check-action-secrets.yml
          .github/workflows/codeowners-validator.yml
          .github/workflows/codeql-analysis.yml
          .github/workflows/codespell.yml
          .github/workflows/rebase-dependabot-pull-requests.yml
          .github/workflows/release-drafter.yml
          .github/workflows/sync-with-template.yml
