name: Issue assignment

on:
  issues:
    types:
    - opened
    - transferred

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
    - name: Auto-assign issue
      uses: pozil/auto-assign-issue@v1
      with:
        assignees: ${{secrets.DEFAULT_ISSUE_ASSIGNEE || 'remal'}}
